### ISSUE TITLE
🐛 Bug: Mixed case column names from Source S3 is causing empty data when loaded to DuckDB 

### ISSUE THREAD

**Issue by divyagowdab** [airbytehq/PyAirbyte#108]
I tried to read data from a s3 source. The bucket had one csv file. Attached the sample csv file.
In the attached file there are 2 colums starting with upper case (Age and Credit_rating). For those 2 columns the duck db does not have data. (attached screenshot)
If i change all the column names to lower case then everything works fine.
And also if the column names are hyphen separated then "missing column" error is thrown.
[TestData.csv](https://github.com/airbytehq/PyAirbyte/files/14529523/TestData.csv)
<img width="1081" alt="Screenshot 2024-03-08 at 1 43 47 AM" src="https://github.com/airbytehq/PyAirbyte/assets/96168512/86aeabd7-3198-4ce5-aad3-62cbdd4f3142">

**Comment by aaronsteers** [comment]
@divyagowdab - This is very helpful feedback - thank you.

We will see if I can reproduce this using the `File` source, and will report back.

**Comment by aaronsteers** [comment]
@divyagowdab - We have a PR ready for review, which should resolve this: #114
