### ISSUE TITLE
Bug: permission error in source_check() for venv-source-faker (Windows issue)

### ISSUE THREAD

**Issue by bindipankhudi** [airbytehq/PyAirbyte#130]
Isssue reported by Carsten Hohnke in slack: 

Now getting permission error in source_check() when venv-source-faker trying to access c:/.../appdata/local/temp/tmpxxxx during _read_json_file in connector.py that I haven't been able to trace.

Trace included in screenshots:

![image (2)](https://github.com/airbytehq/PyAirbyte/assets/158614730/ead198ac-ba2e-47c8-80b3-196994164124)
![image (3)](https://github.com/airbytehq/PyAirbyte/assets/158614730/3baf377d-e6c7-4d5e-9725-484a868e86c4)

**Comment by aaronsteers** [comment]
@bindipankhudi - I think this may be related to:

- #100 

Fix WIP: 

- #100

**Comment by aaronsteers** [comment]
@bindipankhudi - Now that #100 has merged and released, this can be retested in the latest v0.7.6 version.

**Comment by aaronsteers** [comment]
@bindipankhudi - I believe this is resolved. Please re-open if issues persist.
