### ISSUE TITLE
Research top failing connectors in PyAirbyte

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte#142]
![Image](https://github.com/airbytehq/PyAirbyte/assets/18150651/375a4eed-f511-4255-8161-67c443a86fcb)

**Comment by bindipankhudi** [comment]
Stats from some of the failing connectors: https://docs.google.com/spreadsheets/d/13bhLYooDGqhYgqkyuvAWZm9zjbuhm_r1A6dUrosT2NU/edit?usp=sharing
