### ISSUE TITLE
💡 Feature Request: Add `to_arrow()` on `Dataset` class

### ISSUE THREAD

**Issue by oberalppaolof** [airbytehq/PyAirbyte#204]
Arrow is a crucial library and support it natively is a big opportunity. So we can avoid to use to_pandas().

**Comment by avirajsingh7** [comment]
Hey @aaronsteers can you assign me this one?

**Comment by aaronsteers** [comment]
@avirajsingh7 - It's yours! Thanks for volunteering!

**Comment by avirajsingh7** [comment]
@aaronsteers is this correct idea to convert data into pandas then into arrow,

```
    def get_arrow_table(self, stream_name: str) -> pa.Table:
        table_name = self._read_processor.get_sql_table_name(stream_name)
        engine = self.get_sql_engine()
        
        df = pd.read_sql_table(table_name, engine, schema=self.schema_name)
        return pa.Table.from_pandas(df)
```

or I should process data from table using _read_processor

**Comment by aaronsteers** [comment]
@avirajsingh7 - I think that is a decent default implementation. However, this approach will require that the entire dataset fits into memory. 

I've done some [research](https://chatgpt.com/share/1e798b81-6d02-4b99-a4fa-d7da6f719c4e) on my side and I think what we want here is to return a pyarrow `Dataset` object.

For large datasets that will not fit into memory, I believe the `Dataset` construct will allow us to break the entire table's data into chunks when necessary, avoiding crashing in scenarios where RAM is limited or the data size is just huge. 

In terms of the actual implementation, I don't think we need to have very complex handing at this time. As long as the return type will allow us to refactor in the future, we should be good with an implementation that just puts the whole thing in memory, similar to your example above.

**Comment by avirajsingh7** [comment]
@aaronsteers pd.read_sql_table has option for [chunk_size](https://pandas.pydata.org/docs/reference/api/pandas.read_sql_table.html), 
<img width="779" alt="Screenshot 2024-06-25 at 10 47 51 PM" src="https://github.com/airbytehq/PyAirbyte/assets/100823015/b08e8e89-6e2e-4f73-9f30-c7aaa85ac4eb">

We can get actual dataset in smaller pandas dataframe and creating a pyarrow_tables from them,

Later on returning [pyarrow dataset](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.dataset.html) to users,
```

    def get_arrow_dataset(self, stream_name: str) :
        
        table_name = self._read_processor.get_sql_table_name(stream_name)
        engine = self.get_sql_engine()
        
        chunks = pd.read_sql_table(table_name, engine, schema=self.schema_name,chunksize=500000)

        first_chunk = next(chunks)
        combined_schema = pa.Schema.from_pandas(first_chunk)
        arrow_tables = []

        pa.Table.from_pandas(first_chunk, schema=combined_schema)
        for chunk in chunks:

            # Convert each chunk to Arrow Table
            chunk_arrow_table = pa.Table.from_pandas(chunk, schema=combined_schema)
            arrow_tables.append(chunk_arrow_table)

        dataset = pa.dataset.dataset(arrow_tables)
        return dataset
```

What are your views on this approach?

**Comment by avirajsingh7** [comment]
@aaronsteers Raised PR for this one
