### ISSUE TITLE
Update snowflake-python-connector dependency to address security risk

### ISSUE THREAD

**Issue by BarSimovich** [airbytehq/PyAirbyte#221]
PyAirbyte currently has a dependency on `snowflake-python-connector==3.6.0`, which in turn depends on an outdated version of the `cryptography` library (<4.2). This outdated version poses a security risk.

To mitigate this risk, it's recommended to update the `snowflake-python-connector` dependency to a version that uses a more recent `cryptography` version (>=4.2).

Please consider updating the dependency to ensure a secure environment for PyAirbyte users.

**Comment by aaronsteers** [comment]
@BarSimovich - Thanks very much for raising this. A PR is welcome - and otherwise we'll try to get to this in the current iteration.

**Comment by aaronsteers** [comment]
@BarSimovich - This has merged and will be released in PyAirbyte 0.11.0, ETA later today or tomorrow.
