### ISSUE TITLE
🐛 Bug: Syncs show "0 records" synced in the summary without mentioning that the sync was in incremental mode (no *new* records)

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte#237]
This has frequently been a cause of confusion for users. When PyAirbyte is syncing after the first sync, the fact that it is using incremental logic is not obvious in the print statements and summaries. So "0 records" synced looks like a bug, when in reality there's just nothing _new_ since the last sync operation.

**Comment by avirajsingh7** [comment]
@aaronsteers assign me this one

**Comment by avirajsingh7** [comment]
@aaronsteers a nice logger msg showing this is incremental sync, should be enough for this one,
and all adding if you want to use full referesh use force_full_refresh as args
LMK

**Comment by aaronsteers** [comment]
Closing as complete (merged). Thank you, @avirajsingh7 !
