### ISSUE TITLE
Blog post: Using Custom Python connectors with PyAirbyte

### ISSUE THREAD

**Issue by bindipankhudi** [airbytehq/PyAirbyte#247]
## Summary

This blog post would focus on how to build custom python connectors and then executing them from PyAirbyte.

## Definition of Done

Blog post illustrating how to build custom python connectors and then executing them from PyAirbyte.

Article should cover:

- Basic instruction on how to start building and testing a Python-based source connector.
- How to install and test a Python connector in PyAirbyte using `pip_url` of local path.
- Show example for installing a Python connector in PyAirbyte using `pip_url` of a git repo and/or with the `pip_url` of a git feature branch.
- Any suggestions for debugging / troubleshooting which seem relevant for this use case.

## Resources to Assist

- PyAirbyte tutorials: https://github.com/airbytehq/quickstarts/tree/main/pyairbyte_notebooks
- PyAirbyte Documentaton: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started 
- PyAirbyte API Reference: https://docs.airbyte.com/using-airbyte/pyairbyte/getting-started#api-reference
- Sample blog post: https://airbyte.com/blog/manage-and-orchestrate-airbyte-connections-using-python

**Comment by avirajsingh7** [comment]
@bindipankhudi I want to work on this issue for hackathon

**Comment by avirajsingh7** [comment]
@aaronsteers i think both this issue are same https://github.com/airbytehq/PyAirbyte-Hackathon/issues/7

**Comment by Harmaton** [comment]
I want to work on this tutorial

**Comment by aaronsteers** [comment]
@avirajsingh7 - Apologies for the confusion. I've updated this issue's description and title to target Python connectors, specifically, focusing on local testing and how to run from feature branches during development. I've also clarified the similar item to focus more clearly on no-code developer, which outputs the connector definition as a yaml file.

Let me know if this is still interesting - and if so, let me know if I can provide any additional resources to assist or clarify. Thanks!

**Comment by marcosmarxm** [comment]
@topefolorunso do you want to work on this one?

**Comment by Harmaton** [comment]
Assign this to me @marcosmarxm

**Comment by marcosmarxm** [comment]
@Harmaton do you need any help here?

**Comment by Harmaton** [comment]
@marcosmarxm I have this [doc](https://docs.google.com/document/d/1AmFghhnKk1JL5hh93CYkQhjKPTMuCcBJ0qarw5sJdXE/edit)  ready. However, I am having an issue using ```pip_url```    , could you please provide an example of the command.

**Comment by Harmaton** [comment]
I think thats all then I can submir for review

**Comment by Harmaton** [comment]
If done. can you assign issue #19

**Comment by aaronsteers** [comment]
I completed a review and it looks good for my part. I'll let @marcosmarxm handle next steps during his working hours tomorrow. (Today is a US / company holiday.)

**Comment by Harmaton** [comment]
@marcosmarxm

**Comment by marcosmarxm** [comment]
@Harmaton you can proceed to the next challenge. I'll post this in Airbyte blog.

**Comment by Harmaton** [comment]
Please mark as done while at it. I know You have my bio. Thank you!
