### ISSUE TITLE
 duckdb-engine==0.9.2

### ISSUE THREAD

**Issue by estaar** [airbytehq/PyAirbyte#267]
The dependency on ` duckdb==0.9.2` creates an installation error. I have tried in WSL and normal windows Virtual environment.
It gives an error:
`Failed to build duckdb pendulum`
`ERROR: Could not build wheels for duckdb, pendulum, which is required to install pyproject.toml-based projects`

I am able to install higher version of `duckdb` without any error as well as `pendulum`

**Comment by aaronsteers** [comment]
@estaar - We just released PyAirbyte `0.12.0` - which bumps DuckDB to the brand new "1.0" version. Let us know if this fixes your issue! Thanks!

**Comment by aaronsteers** [comment]
Closing as resolved.
