### ISSUE TITLE
Building Data chat agent with PyAirbyte  Polygon.io source & Langchain

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/PyAirbyte#284]
**Summary**
This goal of this task is to show uses how to use [polygon.io](http://polygon.io/) as a data source and use the langchain experimental agent

**Project Description**
This issue broadly involves the following
Set up a Airbyte cloud connection using the mentioned source and destinations, and move some data (Option to use PyAirbyte)
Perform Chat on the data in the mentioned destination. You can choose to do Chat on the data using OpenAI/LangChain, or any other means of your choice.

**Definition of Done**
Deliver documentation (Blog post, Python notebook, etc.) covering end to end steps including code snippets when applicable. When providing a python notebook, please add a "What / Why / How" blurb at the top to explain what the code is doing.

**Use Case**
Chat with your numerical data

**Comment by bala-ceg** [comment]
Hi @marcosmarxm, 
Can you please assign this issue to me?

**Comment by bala-ceg** [comment]
Draft Notebook for the PR is here https://colab.research.google.com/drive/12zC5B_1m-buFvi28g1--uiITxGws9te1?usp=sharing

**Comment by bleonard** [comment]
This was also in https://github.com/airbytehq/quickstarts/pull/129
