### ISSUE TITLE
End to End Rag using Github, Pyairbyte and Weaviate

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/PyAirbyte#286]
Goal is to create python notebook that serves as a quickstart guide for utilizing Weaviate as a destination for RAG workflows using Github as a source and pyairbyte. (edited)

**Comment by pangeran-bottor** [comment]
@marcosmarxm I would like to work on this

**Comment by gupta-arpan** [comment]
@marcosmarxm i would like to work on this.

**Comment by gupta-arpan** [comment]
@marcosmarxm i would like to work on this. @pangeran-bottor i will appreciate if you let me do this as this issue is suggested by me.

**Comment by gupta-arpan** [comment]
@marcosmarxm can you please assign me this issue .

**Comment by marcosmarxm** [comment]
@pangeran-bottor this was suggested by @gupta-arpan so he has the preference, sorry about that :(

**Comment by pangeran-bottor** [comment]
no worries, thanks @marcosmarxm

**Comment by bleonard** [comment]
Merged https://github.com/airbytehq/quickstarts/pull/132
