### ISSUE TITLE
End-to-end RAG tutorial using Salesforce data , Airbyte Cloud and Weaviate:

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/PyAirbyte#287]
This goal of this task is to show uses how to use Salesforce as a data source for their Weaviate based vector store, and to implement a short RAG demo based on the loaded data.

**Comment by ombhardwajj** [comment]
Please assign it to me @marcosmarxm

**Comment by ombhardwajj** [comment]
Link to the draft blog ---> [BLOG](https://hashnode.com/preview/6682406cfb651b4af0e7a3a7)

**Comment by ombhardwajj** [comment]
Hey @marcosmarxm I've linked a PR and posted the draft blog for this!

**Comment by bleonard** [comment]
We will look into publishing. Thank you for your contribution.

**Comment by ombhardwajj** [comment]
@bleonard  I think you forgot to review/merge the PR! [see this](https://github.com/airbytehq/quickstarts/pull/131)
