### ISSUE TITLE
Auto-locate and inject matching secrets as needed

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte#54]
_Originally tracked in [#1](https://github.com/airbytehq/PyAirbyte/issues/1#issuecomment-1955720461)_

## Secrets management Phase 2. Auto-detect and inject
In this phase, presumably we'd be able to auto-inject secrets if they match a specific naming convention that aligns with the source name and setting name.

Tech Spec here:

https://docs.google.com/document/d/1rqoRuGRDvSYX8TmtxvpJv-XJgzfN46fLYtuMymz-QE8/edit#heading=h.c4ztxwwo0ign

## Re: Priority

We can probably postpone/deprioritize this one for a little while. It will be most valuable we want the same secret value to be applicable from both local and hosted execution models.

**Comment by bindipankhudi** [comment]
To be done prior to https://github.com/airbytehq/PyAirbyte/issues/33
