### ISSUE TITLE
Refactor progress indicator and make optional

### ISSUE THREAD

**Issue by flash1293** [airbytehq/PyAirbyte#6]
Currently the progress indicator in airbyte-lib has several problems:
* Managed globally and either takes over the whole terminal view all the time or is disabled completely
* Incompatible with features like prompting the user for input
* No way for user to control whether it's shown or not

To fix these issues, the feature should be refactored:
* Manage state via local instance
* Enable for the duration of the sync, then disable again for maximum compatibility
* Allow to enable/disable via argument on `read` / env var, with smart default based on detected environment (e.g. in CI disable)

**Comment by aaronsteers** [comment]
Improved but not fully resolved:

- https://github.com/airbytehq/airbyte/pull/34973
