### ISSUE TITLE
Docs: Add instructions on how to use PyAirbyte with LangChain

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte#92]
We don't have an entry in our own docs yet for the LangChain integration.

There are really two ways to integrate...

## LangChain native integration (`airbyte-langchain`)

Erick shows this really well:

- LinkedIn: https://www.linkedin.com/posts/langchain_universal-document-loader-with-langchain-airbyte-activity-7169410958346444801-6hYa/
- Docs: https://python.langchain.com/docs/integrations/document_loaders/airbyte
- YouTube: https://www.youtube.com/watch?v=zQU_1sCLSMU

## PyAirbyte-centric integration

You can also directly use PyAirbyte to create documents and send them to LangChain without importing `airbyte-langchain`.

Example here:

https://colab.research.google.com/drive/1IiP224qBttdSVYA31mutgokDsMk-1DAq#scrollTo=I7COppv6yGpv

**Comment by cornzyblack** [comment]
Hi @aaronsteers, I would like to work on this, to add the instructions, would Docs involve adding a README.md to the docs folder or is there a specific starter file that needs to be modified?

**Comment by bindipankhudi** [comment]
Hi @cornzyblack, thank you for offering to help with this. :) Really appreciate it! Since this is a new integration, we prefer someone on the Airbyte team to handle the documentation. If another issue seems interesting to you to work on, please feel free to ping us.
